# Generated by Django 4.1.2 on 2022-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
