# Generated by Django 4.1.2 on 2022-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
