# Generated by Django 4.1.2 on 2022-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0002_alter_participant_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
