# Generated by Django 4.1.2 on 2022-11-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_photo'),
        ('participant', '0003_alter_participant_first_name_and_more'),
    ]

    operations = [
    ]
