version: "3"

services:
  db:
    image: mysql:8
    environment:
       MYSQL_DATABASE: "innowebdb"
       MYSQL_USER: "innosoft"
       MYSQL_PASSWORD: "innosoft-2022"
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_HOST_NAME: "localhost"
       MYSQL_TCP_PORT: "3307"
    ports:
    - "3306:3307"

  web:
    image: innosoftinnoweb/innosoft-innoweb-1:main
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure

