version: "3"

services: 
  db:
    image: mysql:8
    environment:
       MYSQL_DATABASE: "innowebdb"
       USER: "innosoft"
       PASSWORD: "innosoft-2022"
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_HOST_NAME: "localhost"
    ports:
      - "3306:3307"
    command: 
      - --default-authentication-plugin=mysql_native_password
   
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

          
