version: '3'

services: 
  db:
    image: mysql:8
    ports:
      - '3306:3307'
    environment:
       MYSQL_DATABASE: 'innowebdb'
       MYSQL_USER: 'innosoft'
       MYSQL_PASSWORD: 'innosoft-2022'
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_HOST_NAME: 'localhost'
    

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

          
