# Generated by Django 4.1.2 on 2022-11-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='punctuation',
        ),
        migrations.AddField(
            model_name='score',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
