# Generated by Django 4.1.2 on 2022-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del evento', max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('place', models.CharField(help_text='Lugar del evento', max_length=100)),
                ('photo', models.URLField(blank=True, help_text='Url de la imagen del evento', max_length=10000)),
                ('status', models.CharField(choices=[('Abierto', 'Abierto'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='Abierto', max_length=100)),
            ],
        ),
    ]
