# Generated by Django 4.1.2 on 2022-11-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.URLField(blank=True, help_text='Url de la imagen del evento', max_length=10000),
        ),
    ]
