# Generated by Django 4.1.2 on 2022-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introducce tu nombre', max_length=50)),
                ('apellidos', models.CharField(help_text='Introduce tus apellidos', max_length=50)),
                ('correo', models.EmailField(help_text='Introduce tu correo', max_length=50)),
                ('foto', models.URLField(help_text='Introduce la url de tu foto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
