# Generated by Django 4.1.2 on 2022-10-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='evento')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='Abierto', max_length=100)),
            ],
        ),
    ]
